language: node_js
node_js:
  - stable
  - "8"
  - "6"
jobs:
  include:
    - stage: Produce Coverage
      node_js: stable
      script: jest --coverage && cat ./coverage/lcov.info | ./node_modules/coveralls/bin/coveralls.js && rm -rf ./coverage
